
package com.reactiveworks.stocktrade.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Mon Mar 23 11:11:24 PDT 2020
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "getStockTrades", namespace = "http://webservice.stocktrade.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStockTrades", namespace = "http://webservice.stocktrade.reactiveworks.com/")

public class GetStockTrades {


}

