package com.reactiveworks.stocktrade.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-23T17:38:21.349-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", name = "StockTradeWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface StockTradeWebService {

    @WebMethod
    @RequestWrapper(localName = "getDailyTradingDifferential", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetDailyTradingDifferential")
    @ResponseWrapper(localName = "getDailyTradingDifferentialResponse", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetDailyTradingDifferentialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper getDailyTradingDifferential(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMaxVolumeTrade", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetMaxVolumeTrade")
    @ResponseWrapper(localName = "getMaxVolumeTradeResponse", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetMaxVolumeTradeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.reactiveworks.stocktrade.webservice.StockTrade getMaxVolumeTrade(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStockTrades", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetStockTrades")
    @ResponseWrapper(localName = "getStockTradesResponse", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetStockTradesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> getStockTrades() throws StockTradeServiceFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMinVolumeTrade", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetMinVolumeTrade")
    @ResponseWrapper(localName = "getMinVolumeTradeResponse", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/", className = "com.reactiveworks.stocktrade.webservice.GetMinVolumeTradeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.reactiveworks.stocktrade.webservice.StockTrade getMinVolumeTrade(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0
    );
}
