package com.reactiveworks.stocktrade.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-23T17:38:21.356-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "StockTradeWebServiceService", 
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap-webservice/soap-exercise/stocktradeclient/WebContent/wsdl/stocktradewebservice.wsdl",
                  targetNamespace = "http://webservice.stocktrade.reactiveworks.com/") 
public class StockTradeWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.stocktrade.reactiveworks.com/", "StockTradeWebServiceService");
    public final static QName StockTradeWebServicePort = new QName("http://webservice.stocktrade.reactiveworks.com/", "StockTradeWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap-webservice/soap-exercise/stocktradeclient/WebContent/wsdl/stocktradewebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StockTradeWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap-webservice/soap-exercise/stocktradeclient/WebContent/wsdl/stocktradewebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StockTradeWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockTradeWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockTradeWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StockTradeWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StockTradeWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StockTradeWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StockTradeWebService
     */
    @WebEndpoint(name = "StockTradeWebServicePort")
    public StockTradeWebService getStockTradeWebServicePort() {
        return super.getPort(StockTradeWebServicePort, StockTradeWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockTradeWebService
     */
    @WebEndpoint(name = "StockTradeWebServicePort")
    public StockTradeWebService getStockTradeWebServicePort(WebServiceFeature... features) {
        return super.getPort(StockTradeWebServicePort, StockTradeWebService.class, features);
    }

}
