
package com.reactiveworks.stocktrade.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-23T17:38:21.327-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "StockTradeServiceFailureException", targetNamespace = "http://webservice.stocktrade.reactiveworks.com/")
public class StockTradeServiceFailureException_Exception extends Exception {
    
    private com.reactiveworks.stocktrade.webservice.StockTradeServiceFailureException stockTradeServiceFailureException;

    public StockTradeServiceFailureException_Exception() {
        super();
    }
    
    public StockTradeServiceFailureException_Exception(String message) {
        super(message);
    }
    
    public StockTradeServiceFailureException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public StockTradeServiceFailureException_Exception(String message, com.reactiveworks.stocktrade.webservice.StockTradeServiceFailureException stockTradeServiceFailureException) {
        super(message);
        this.stockTradeServiceFailureException = stockTradeServiceFailureException;
    }

    public StockTradeServiceFailureException_Exception(String message, com.reactiveworks.stocktrade.webservice.StockTradeServiceFailureException stockTradeServiceFailureException, Throwable cause) {
        super(message, cause);
        this.stockTradeServiceFailureException = stockTradeServiceFailureException;
    }

    public com.reactiveworks.stocktrade.webservice.StockTradeServiceFailureException getFaultInfo() {
        return this.stockTradeServiceFailureException;
    }
}
