
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.stocktrade.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-03-23T17:38:21.335-07:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "StockTradeWebServiceService",
                      portName = "StockTradeWebServicePort",
                      targetNamespace = "http://webservice.stocktrade.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap-webservice/soap-exercise/stocktradeclient/WebContent/wsdl/stocktradewebservice.wsdl",
                      endpointInterface = "com.reactiveworks.stocktrade.webservice.StockTradeWebService")
                      
public class StockTradeWebServicePortImpl implements StockTradeWebService {

    private static final Logger LOG = Logger.getLogger(StockTradeWebServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.stocktrade.webservice.StockTradeWebService#getDailyTradingDifferential(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0)*
     */
    public com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper getDailyTradingDifferential(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0) { 
        LOG.info("Executing operation getDailyTradingDifferential");
        System.out.println(arg0);
        try {
            com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper _return = new com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper();
            com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff _returnDailyTrdDiff = new com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff();
            java.util.List<com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff.Entry> _returnDailyTrdDiffEntry = new java.util.ArrayList<com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff.Entry>();
            com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff.Entry _returnDailyTrdDiffEntryVal1 = new com.reactiveworks.stocktrade.webservice.DailyTradingDiffWrapper.DailyTrdDiff.Entry();
            _returnDailyTrdDiffEntryVal1.setKey(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-23T17:38:21.345-07:00"));
            _returnDailyTrdDiffEntryVal1.setValue(Double.valueOf(0.10829894334778944));
            _returnDailyTrdDiffEntry.add(_returnDailyTrdDiffEntryVal1);
            _returnDailyTrdDiff.getEntry().addAll(_returnDailyTrdDiffEntry);
            _return.setDailyTrdDiff(_returnDailyTrdDiff);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.stocktrade.webservice.StockTradeWebService#getMaxVolumeTrade(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0)*
     */
    public com.reactiveworks.stocktrade.webservice.StockTrade getMaxVolumeTrade(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0) { 
        LOG.info("Executing operation getMaxVolumeTrade");
        System.out.println(arg0);
        try {
            com.reactiveworks.stocktrade.webservice.StockTrade _return = new com.reactiveworks.stocktrade.webservice.StockTrade();
            _return.setAdjClose(Double.valueOf(0.8531093372093774));
            _return.setClose(Double.valueOf(0.051524607929481325));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-23T17:38:21.346-07:00"));
            _return.setHigh(Double.valueOf(0.9909004470524256));
            _return.setLow(Double.valueOf(0.4859315006532069));
            _return.setOpen(Double.valueOf(0.1595229877030082));
            _return.setSecurity("Security-1651389490");
            _return.setVolume(Double.valueOf(0.16491564960345884));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.stocktrade.webservice.StockTradeWebService#getStockTrades()*
     */
    public java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> getStockTrades() throws StockTradeServiceFailureException_Exception   { 
        LOG.info("Executing operation getStockTrades");
        try {
            java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> _return = new java.util.ArrayList<com.reactiveworks.stocktrade.webservice.StockTrade>();
            com.reactiveworks.stocktrade.webservice.StockTrade _returnVal1 = new com.reactiveworks.stocktrade.webservice.StockTrade();
            _returnVal1.setAdjClose(Double.valueOf(0.03749612236507904));
            _returnVal1.setClose(Double.valueOf(0.030942696669126635));
            _returnVal1.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-23T17:38:21.347-07:00"));
            _returnVal1.setHigh(Double.valueOf(0.34711043534352437));
            _returnVal1.setLow(Double.valueOf(0.815618271542474));
            _returnVal1.setOpen(Double.valueOf(0.2373333250174139));
            _returnVal1.setSecurity("Security-860339938");
            _returnVal1.setVolume(Double.valueOf(0.9090506301466813));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StockTradeServiceFailureException_Exception("StockTradeServiceFailureException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.stocktrade.webservice.StockTradeWebService#getMinVolumeTrade(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0)*
     */
    public com.reactiveworks.stocktrade.webservice.StockTrade getMinVolumeTrade(java.util.List<com.reactiveworks.stocktrade.webservice.StockTrade> arg0) { 
        LOG.info("Executing operation getMinVolumeTrade");
        System.out.println(arg0);
        try {
            com.reactiveworks.stocktrade.webservice.StockTrade _return = new com.reactiveworks.stocktrade.webservice.StockTrade();
            _return.setAdjClose(Double.valueOf(0.8930849891276349));
            _return.setClose(Double.valueOf(0.6033710056193085));
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-23T17:38:21.348-07:00"));
            _return.setHigh(Double.valueOf(0.5695334329457138));
            _return.setLow(Double.valueOf(0.9558057541123068));
            _return.setOpen(Double.valueOf(0.8433413539893091));
            _return.setSecurity("Security-1063276883");
            _return.setVolume(Double.valueOf(0.21615773703872798));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
